---

# self-hosted-answers
engine_fqdn: ovirt-engine.example.com
engine_vm_ram: "{{ 4096 if compatibility_version < 4.1 else 16384 }}"
engine_vm_cpus: "{{ 2 if compatibility_version < 4.1 else 4 }}"
engine_setup_timeout: 3600
gateway: '{{ ansible_default_ipv4.gateway }}'
interface_name: '{{ ansible_default_ipv4.interface }}'
cluster_name: Default
storage_datacenter_name: hosted_storage
hosted_storage_type: nfs
storage_domain_type: "{{ 'nfs3' if hosted_storage_type == 'nfs' else 'glusterfs' if hosted_storage_type == 'gluster' else 'fc' if hosted_storage_type == 'fcp' else hosted_storage_type }}"
hosted_storage_name: my_hosted_storage
hosted_storage_address: localhost
hosted_storage_path: /path/to/storage
hosted_storage_lun: none:None
hosted_iscsi_portal_port: 3260
hosted_iscsi_portal_ip_address: '{{ hosted_storage_address }}'
vm_timezone: America/New_York

engine_mac_address: '00:11:22:33:44:55'
cpu_model: model_Nehalem
root_password: changeme
admin_password: changeme
config_dir: /etc/ansible-ovirt
host_id: 1
host_name: hosted_engine_{{ host_id }}
compatibility_version: 4.0
# product stand for decide to install ovirt/rhv appliance
product: ovirt
package_name: "{{ 'rhevm-appliance' if compatibility_version < 4.1 else 'rhvm-appliance' }}"
ssh_authorized_keys: []
engine_application_mode: virt
engine_organization: localdomain

# user-data
ovirt_engine_db_host: localhost
ovirt_engine_db_user: engine
ovirt_engine_db_name: engine
ovirt_engine_db_port: 5432
ovirt_engine_db_password: dbpassword

# set dwh default values
ovirt_engine_dwh_db_host: localhost
ovirt_engine_dwh_db_user: ovirt_engine_history
ovirt_engine_dwh_db_name: ovirt_engine_history
ovirt_engine_dwh_db_port: 5432
ovirt_engine_dwh_db_password: dbpassword
